# Generated by Django 4.2.15 on 2024-08-15 00:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('servicios', '0002_alter_servicio_ser_nombre'),
    ]

    operations = [
        migrations.CreateModel(
            name='Atencion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ate_numero', models.CharField(max_length=20, unique=True)),
                ('ate_monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ate_observacion', models.CharField(max_length=200, null=True)),
                ('ate_fecha', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cli_dni', models.IntegerField(unique=True)),
                ('cli_nombre', models.CharField(max_length=50)),
                ('cli_apellido', models.CharField(max_length=50)),
                ('cli_celular', models.CharField(max_length=20)),
                ('cli_email', models.EmailField(max_length=50, null=True)),
                ('cli_red_social', models.CharField(max_length=50, null=True)),
                ('cli_domicilio', models.CharField(max_length=100, null=True)),
                ('cli_fecha_nacimiento', models.DateTimeField(null=True)),
                ('cli_fecha_alta', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FormaPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fp_nombre', models.CharField(max_length=30, unique=True)),
                ('fp_interes', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='DetalleAtencion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('da_cantidad', models.IntegerField(default=1)),
                ('da_atencion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='atenciones.atencion')),
                ('da_servicio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='servicios.servicio')),
                ('da_usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='atencion',
            name='ate_cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='atenciones.cliente'),
        ),
    ]
