# Generated by Django 4.2.15 on 2024-08-15 05:41

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('atenciones', '0002_atencion_ate_cantidad_atencion_ate_servicio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='atencion',
            name='ate_forma_pago',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.RESTRICT, to='atenciones.formapago'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='atencion',
            name='ate_fecha',
            field=models.DateField(default=datetime.datetime.today, null=True),
        ),
    ]
