# Generated by Django 4.2.15 on 2024-08-15 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atenciones', '0003_atencion_ate_forma_pago_alter_atencion_ate_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='atencion',
            name='ate_imagen',
            field=models.ImageField(blank=True, null=True, upload_to='atenciones'),
        ),
    ]
