# Generated by Django 4.2.15 on 2024-08-07 00:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gasto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gas_nombre', models.CharField(max_length=50)),
                ('gas_descripcion', models.CharField(max_length=100)),
                ('gas_monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('gas_fecha', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ser_nombre', models.CharField(max_length=50)),
                ('ser_descripcion', models.CharField(default='descripcion', max_length=100)),
                ('ser_duracion', models.IntegerField(default=10)),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('st_actual', models.IntegerField()),
                ('st_minimo', models.IntegerField()),
                ('st_maximo', models.IntegerField(null=True)),
                ('st_fecha_actualizacion', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Insumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ins_codigo', models.CharField(max_length=20)),
                ('ins_nombre', models.CharField(max_length=50)),
                ('ins_marca', models.CharField(max_length=50)),
                ('ins_unidad_medida', models.CharField(max_length=20)),
                ('ins_contenido', models.IntegerField()),
                ('ins_descripcion', models.CharField(max_length=100)),
                ('ins_stock', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.stock')),
            ],
        ),
    ]
