# Generated by Django 4.2.15 on 2024-08-12 01:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_delete_servicio'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Gasto',
        ),
    ]
