# Generated by Django 4.2.15 on 2024-08-12 23:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_delete_gasto'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Insumo',
        ),
        migrations.DeleteModel(
            name='Stock',
        ),
    ]
