# Generated by Django 4.2.15 on 2024-08-12 23:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mar_nombre', models.CharField(max_length=50)),
                ('mar_descripcion', models.CharField(max_length=100, null=True)),
                ('mar_fecha_alta', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('st_actual', models.IntegerField()),
                ('st_minimo', models.IntegerField()),
                ('st_maximo', models.IntegerField(null=True)),
                ('st_fecha_actualizacion', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Insumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ins_codigo', models.CharField(max_length=20)),
                ('ins_nombre', models.CharField(max_length=50)),
                ('ins_unidad_medida', models.CharField(max_length=20)),
                ('ins_contenido', models.IntegerField()),
                ('ins_descripcion', models.CharField(max_length=100)),
                ('ins_marca', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='insumos.marca')),
                ('ins_stock', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='insumos.stock')),
            ],
        ),
    ]
