# Generated by Django 4.2.15 on 2024-08-13 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insumos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insumo',
            name='ins_codigo',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
