# Generated by Django 4.2.15 on 2024-08-13 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insumos', '0002_alter_insumo_ins_codigo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marca',
            name='mar_nombre',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
