# Generated by Django 4.2.15 on 2024-08-14 00:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('insumos', '0003_alter_marca_mar_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insumo',
            name='ins_stock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='insumos.stock'),
        ),
    ]
