# Generated by Django 4.2.15 on 2024-08-14 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insumos', '0004_alter_insumo_ins_stock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='insumo',
            name='ins_stock',
        ),
        migrations.AddField(
            model_name='insumo',
            name='ins_stock_actual',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='insumo',
            name='ins_stock_maximo',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='insumo',
            name='ins_stock_minimo',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Stock',
        ),
    ]
