# Generated by Django 4.2.15 on 2024-08-10 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ser_nombre', models.CharField(max_length=50)),
                ('ser_descripcion', models.CharField(default='descripcion', max_length=100)),
                ('ser_duracion', models.IntegerField(default=10)),
            ],
        ),
    ]
