# Generated by Django 4.2.15 on 2024-08-13 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicio',
            name='ser_nombre',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
