# Generated by Django 4.2.15 on 2024-08-12 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gasto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gas_nombre', models.CharField(max_length=50)),
                ('gas_descripcion', models.CharField(max_length=100)),
                ('gas_monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('gas_fecha', models.DateField()),
            ],
        ),
    ]
